(define items1 (list 1 3 (list 5 7) 9))
(define items2 (list (list 7)))
(define items3 (list 1 (list 2 (list 3 (list 4 (list 5 (list 6 7)))))))

(display items1)
(display " ")
(display (cadr (cadr (cdr items1))))
(display " ")
(display items2)
(display " ")
(display (car (car items2)))
(display " ")
(display items3)
(display " ")
(display (cadr (cadr (cadr (cadr (cadr (cadr items3)))))))
