(define (make-account balance password)
        (define (withdraw amount)
                (if (>= balance amount)
                    (begin (set! balance (- balance amount))
                           balance)
                    "Insufficient funds"))
        (define (deposit amount)
                (set! balance (+ balance amount))
                balance)
        (define (dispatch p m)
                (if (eq? p password)
                    (cond ((eq? m 'withdraw) withdraw)
                          ((eq? m 'dispoist) dispoist)
                          (else (error "Unknown request -- MAKE-ACCOUNT" m)))
                    (error "Incorrect password")))
        dispatch)

(define acc (make-account 100 'secret))

(newline)
(display ((acc 'secret 'withdraw) 40))
(newline)
(display ((acc 'other 'deposit) 50))
