(define (ripple-carry-adder a b s c)
        (define (ripple-carry-adder-iter a b s)
                (let ((c (make-wire)))
                     (if (null? a)
                         (set-signal! c 0)
                         (full-adder (car a)
                                     (car b)
                                     (ripple-carry-adder-iter (cdr a)
                                                              (cdr b)
                                                              (cdr s))
                                     (car s)
                                     c))
                     c))
        (full-adder (car a)
                    (car b)
                    (ripple-carry-adder-iter (cdr a)
                                             (cdr b)
                                             (cdr s))
                    (car s)
                    c)
        'ok)
