(define (make-account balance password)
        (define (withdraw amount)
                (if (>= balance amount)
                    (begin (set! balance (- balance amount))
                           balance)
                    "Insufficient funds"))
        (define (deposit amount)
                (set! balance (+ balance amount))
                balance)
        (let ((count 0))
             (lambda (p m)
                     (if (eq? p password)
                         (begin (set! count 0)
                                (cond ((eq? m 'withdraw) withdraw)
                                      ((eq? m 'dispoist) dispoist)
                                      (else (error "Unknown request -- MAKE-ACCOUNT" m))))
                         (if (< count 6)
                             (begin (set! count (+ 1 count))
                                    (lambda (x) "Incorrect password"))
                             (error "call-the-cops"))))))

(define acc (make-account 100 'secret))

(newline)
(display ((acc 'other 'deposit) 50))
(newline)
(display ((acc 'other 'deposit) 50))
(newline)
(display ((acc 'other 'deposit) 50))
(newline)
(display ((acc 'other 'deposit) 50))
(newline)
(display ((acc 'other 'deposit) 50))
(newline)
(display ((acc 'other 'deposit) 50))
(newline)
(display ((acc 'other 'deposit) 50))
