(load "3-66a.scm")

(define (merge-weighted s1 s2 weight)
        (if (< (weight (stream-car s1))
               (weight (stream-car s2)))
            (cons-stream (stream-car s1)
                         (merge-weighted (stream-cdr s1) s2 weight))
            (cons-stream (stream-car s2)
                         (merge-weighted s1 (stream-cdr s2) weight))))

(define (weighted-pairs s t weight)
        (cons-stream (list (stream-car s) (stream-car t))
                     (merge-weighted (stream-map (lambda (x)
                                                         (list (stream-car s) x))
                                                 (stream-cdr t))
                                     (weighted-pairs (stream-cdr s) (stream-cdr t) weight)
                                     weight)))
