(define (make-zero-crossings input-stream last-value last-car)
        (let ((avpt (/ (+ (stream-car input-stream) last-car) 2)))
             (cons-stream (sign-change-detector avpt last-value)
                          (make-zero-crossings (stream-cdr input-stream)
                                               avpt))))
